delete from municipios;
ALTER TABLE municipios AUTO_INCREMENT = 1;
insert into municipios (uf, codigo, municipio) values ('PA', '1500107', 'Abaetetuba');
insert into municipios (uf, codigo, municipio) values ('PA', '1500131', 'Abel Figueiredo');
insert into municipios (uf, codigo, municipio) values ('PA', '1500206', 'Acará');
insert into municipios (uf, codigo, municipio) values ('PA', '1500305', 'Afuá');
insert into municipios (uf, codigo, municipio) values ('PA', '1500347', 'Água Azul do Norte');
insert into municipios (uf, codigo, municipio) values ('PA', '1500404', 'Alenquer');
insert into municipios (uf, codigo, municipio) values ('PA', '1500503', 'Almeirim');
insert into municipios (uf, codigo, municipio) values ('PA', '1500602', 'Altamira');
insert into municipios (uf, codigo, municipio) values ('PA', '1500701', 'Anajás');
insert into municipios (uf, codigo, municipio) values ('PA', '1500800', 'Ananindeua');
insert into municipios (uf, codigo, municipio) values ('PA', '1500859', 'Anapu');
insert into municipios (uf, codigo, municipio) values ('PA', '1500909', 'Augusto Corrêa');
insert into municipios (uf, codigo, municipio) values ('PA', '1500958', 'Aurora do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1501006', 'Aveiro');
insert into municipios (uf, codigo, municipio) values ('PA', '1501105', 'Bagre');
insert into municipios (uf, codigo, municipio) values ('PA', '1501204', 'Baião');
insert into municipios (uf, codigo, municipio) values ('PA', '1501253', 'Bannach');
insert into municipios (uf, codigo, municipio) values ('PA', '1501303', 'Barcarena');
insert into municipios (uf, codigo, municipio) values ('PA', '1501402', 'Belém');
insert into municipios (uf, codigo, municipio) values ('PA', '1501451', 'Belterra');
insert into municipios (uf, codigo, municipio) values ('PA', '1501501', 'Benevides');
insert into municipios (uf, codigo, municipio) values ('PA', '1501576', 'Bom Jesus do Tocantins');
insert into municipios (uf, codigo, municipio) values ('PA', '1501600', 'Bonito');
insert into municipios (uf, codigo, municipio) values ('PA', '1501709', 'Bragança');
insert into municipios (uf, codigo, municipio) values ('PA', '1501725', 'Brasil Novo');
insert into municipios (uf, codigo, municipio) values ('PA', '1501758', 'Brejo Grande do Araguaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1501782', 'Breu Branco');
insert into municipios (uf, codigo, municipio) values ('PA', '1501808', 'Breves');
insert into municipios (uf, codigo, municipio) values ('PA', '1501907', 'Bujaru');
insert into municipios (uf, codigo, municipio) values ('PA', '1501956', 'Cachoeira do Piriá');
insert into municipios (uf, codigo, municipio) values ('PA', '1502004', 'Cachoeira do Arari');
insert into municipios (uf, codigo, municipio) values ('PA', '1502103', 'Cametá');
insert into municipios (uf, codigo, municipio) values ('PA', '1502152', 'Canaã dos Carajás');
insert into municipios (uf, codigo, municipio) values ('PA', '1502202', 'Capanema');
insert into municipios (uf, codigo, municipio) values ('PA', '1502301', 'Capitão Poço');
insert into municipios (uf, codigo, municipio) values ('PA', '1502400', 'Castanhal');
insert into municipios (uf, codigo, municipio) values ('PA', '1502509', 'Chaves');
insert into municipios (uf, codigo, municipio) values ('PA', '1502608', 'Colares');
insert into municipios (uf, codigo, municipio) values ('PA', '1502707', 'Conceição do Araguaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1502756', 'Concórdia do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1502764', 'Cumaru do Norte');
insert into municipios (uf, codigo, municipio) values ('PA', '1502772', 'Curionópolis');
insert into municipios (uf, codigo, municipio) values ('PA', '1502806', 'Curralinho');
insert into municipios (uf, codigo, municipio) values ('PA', '1502855', 'Curuá');
insert into municipios (uf, codigo, municipio) values ('PA', '1502905', 'Curuçá');
insert into municipios (uf, codigo, municipio) values ('PA', '1502939', 'Dom Eliseu');
insert into municipios (uf, codigo, municipio) values ('PA', '1502954', 'Eldorado do Carajás');
insert into municipios (uf, codigo, municipio) values ('PA', '1503002', 'Faro');
insert into municipios (uf, codigo, municipio) values ('PA', '1503044', 'Floresta do Araguaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1503077', 'Garrafão do Norte');
insert into municipios (uf, codigo, municipio) values ('PA', '1503093', 'Goianésia do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1503101', 'Gurupá');
insert into municipios (uf, codigo, municipio) values ('PA', '1503200', 'Igarapé-Açu');
insert into municipios (uf, codigo, municipio) values ('PA', '1503309', 'Igarapé-Miri');
insert into municipios (uf, codigo, municipio) values ('PA', '1503408', 'Inhangapi');
insert into municipios (uf, codigo, municipio) values ('PA', '1503457', 'Ipixuna do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1503507', 'Irituia');
insert into municipios (uf, codigo, municipio) values ('PA', '1503606', 'Itaituba');
insert into municipios (uf, codigo, municipio) values ('PA', '1503705', 'Itupiranga');
insert into municipios (uf, codigo, municipio) values ('PA', '1503754', 'Jacareacanga');
insert into municipios (uf, codigo, municipio) values ('PA', '1503804', 'Jacundá');
insert into municipios (uf, codigo, municipio) values ('PA', '1503903', 'Juruti');
insert into municipios (uf, codigo, municipio) values ('PA', '1504000', 'Limoeiro do Ajuru');
insert into municipios (uf, codigo, municipio) values ('PA', '1504059', 'Mãe do Rio');
insert into municipios (uf, codigo, municipio) values ('PA', '1504109', 'Magalhães Barata');
insert into municipios (uf, codigo, municipio) values ('PA', '1504208', 'Marabá');
insert into municipios (uf, codigo, municipio) values ('PA', '1504307', 'Maracanã');
insert into municipios (uf, codigo, municipio) values ('PA', '1504406', 'Marapanim');
insert into municipios (uf, codigo, municipio) values ('PA', '1504422', 'Marituba');
insert into municipios (uf, codigo, municipio) values ('PA', '1504455', 'Medicilândia');
insert into municipios (uf, codigo, municipio) values ('PA', '1504505', 'Melgaço');
insert into municipios (uf, codigo, municipio) values ('PA', '1504604', 'Mocajuba');
insert into municipios (uf, codigo, municipio) values ('PA', '1504703', 'Moju');
insert into municipios (uf, codigo, municipio) values ('PA', '1504752', 'Mojuí dos Campos');
insert into municipios (uf, codigo, municipio) values ('PA', '1504802', 'Monte Alegre');
insert into municipios (uf, codigo, municipio) values ('PA', '1504901', 'Muaná');
insert into municipios (uf, codigo, municipio) values ('PA', '1504950', 'Nova Esperança do Piriá');
insert into municipios (uf, codigo, municipio) values ('PA', '1504976', 'Nova Ipixuna');
insert into municipios (uf, codigo, municipio) values ('PA', '1505007', 'Nova Timboteua');
insert into municipios (uf, codigo, municipio) values ('PA', '1505031', 'Novo Progresso');
insert into municipios (uf, codigo, municipio) values ('PA', '1505064', 'Novo Repartimento');
insert into municipios (uf, codigo, municipio) values ('PA', '1505106', 'Óbidos');
insert into municipios (uf, codigo, municipio) values ('PA', '1505205', 'Oeiras do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1505304', 'Oriximiná');
insert into municipios (uf, codigo, municipio) values ('PA', '1505403', 'Ourém');
insert into municipios (uf, codigo, municipio) values ('PA', '1505437', 'Ourilândia do Norte');
insert into municipios (uf, codigo, municipio) values ('PA', '1505486', 'Pacajá');
insert into municipios (uf, codigo, municipio) values ('PA', '1505494', 'Palestina do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1505502', 'Paragominas');
insert into municipios (uf, codigo, municipio) values ('PA', '1505536', 'Parauapebas');
insert into municipios (uf, codigo, municipio) values ('PA', '1505551', 'Pau DArco');
insert into municipios (uf, codigo, municipio) values ('PA', '1505601', 'Peixe-Boi');
insert into municipios (uf, codigo, municipio) values ('PA', '1505635', 'Piçarra');
insert into municipios (uf, codigo, municipio) values ('PA', '1505650', 'Placas');
insert into municipios (uf, codigo, municipio) values ('PA', '1505700', 'Ponta de Pedras');
insert into municipios (uf, codigo, municipio) values ('PA', '1505809', 'Portel');
insert into municipios (uf, codigo, municipio) values ('PA', '1505908', 'Porto de Moz');
insert into municipios (uf, codigo, municipio) values ('PA', '1506005', 'Prainha');
insert into municipios (uf, codigo, municipio) values ('PA', '1506104', 'Primavera');
insert into municipios (uf, codigo, municipio) values ('PA', '1506112', 'Quatipuru');
insert into municipios (uf, codigo, municipio) values ('PA', '1506138', 'Redenção');
insert into municipios (uf, codigo, municipio) values ('PA', '1506161', 'Rio Maria');
insert into municipios (uf, codigo, municipio) values ('PA', '1506187', 'Rondon do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1506195', 'Rurópolis');
insert into municipios (uf, codigo, municipio) values ('PA', '1506203', 'Salinópolis');
insert into municipios (uf, codigo, municipio) values ('PA', '1506302', 'Salvaterra');
insert into municipios (uf, codigo, municipio) values ('PA', '1506351', 'Santa Bárbara do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1506401', 'Santa Cruz do Arari');
insert into municipios (uf, codigo, municipio) values ('PA', '1506500', 'Santa Izabel do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1506559', 'Santa Luzia do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1506583', 'Santa Maria das Barreiras');
insert into municipios (uf, codigo, municipio) values ('PA', '1506609', 'Santa Maria do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1506708', 'Santana do Araguaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1506807', 'Santarém');
insert into municipios (uf, codigo, municipio) values ('PA', '1506906', 'Santarém Novo');
insert into municipios (uf, codigo, municipio) values ('PA', '1507003', 'Santo Antônio do Tauá');
insert into municipios (uf, codigo, municipio) values ('PA', '1507102', 'São Caetano de Odivelas');
insert into municipios (uf, codigo, municipio) values ('PA', '1507151', 'São Domingos do Araguaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1507201', 'São Domingos do Capim');
insert into municipios (uf, codigo, municipio) values ('PA', '1507300', 'São Félix do Xingu');
insert into municipios (uf, codigo, municipio) values ('PA', '1507409', 'São Francisco do Pará');
insert into municipios (uf, codigo, municipio) values ('PA', '1507458', 'São Geraldo do Araguaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1507466', 'São João da Ponta');
insert into municipios (uf, codigo, municipio) values ('PA', '1507474', 'São João de Pirabas');
insert into municipios (uf, codigo, municipio) values ('PA', '1507508', 'São João do Araguaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1507607', 'São Miguel do Guamá');
insert into municipios (uf, codigo, municipio) values ('PA', '1507706', 'São Sebastião da Boa Vista');
insert into municipios (uf, codigo, municipio) values ('PA', '1507755', 'Sapucaia');
insert into municipios (uf, codigo, municipio) values ('PA', '1507805', 'Senador José Porfírio');
insert into municipios (uf, codigo, municipio) values ('PA', '1507904', 'Soure');
insert into municipios (uf, codigo, municipio) values ('PA', '1507953', 'Tailândia');
insert into municipios (uf, codigo, municipio) values ('PA', '1507961', 'Terra Alta');
insert into municipios (uf, codigo, municipio) values ('PA', '1507979', 'Terra Santa');
insert into municipios (uf, codigo, municipio) values ('PA', '1508001', 'Tomé-Açu');
insert into municipios (uf, codigo, municipio) values ('PA', '1508035', 'Tracuateua');
insert into municipios (uf, codigo, municipio) values ('PA', '1508050', 'Trairão');
insert into municipios (uf, codigo, municipio) values ('PA', '1508084', 'Tucumã');
insert into municipios (uf, codigo, municipio) values ('PA', '1508100', 'Tucuruí');
insert into municipios (uf, codigo, municipio) values ('PA', '1508126', 'Ulianópolis');
insert into municipios (uf, codigo, municipio) values ('PA', '1508159', 'Uruará');
insert into municipios (uf, codigo, municipio) values ('PA', '1508209', 'Vigia');
insert into municipios (uf, codigo, municipio) values ('PA', '1508308', 'Viseu');
insert into municipios (uf, codigo, municipio) values ('PA', '1508357', 'Vitória do Xingu');
insert into municipios (uf, codigo, municipio) values ('PA', '1508407', 'Xinguara');